--${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --image "{arch}-${{ matrix.addon }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon